--- 
- name: "Check that {{ wordpress_dir }} exist"
  stat:
    path: "{{ wordpress_dir }}" 
  register: dir_exists

- name: Create {{ wordpress_dir }} directory
  file:
    state: directory
    path: "{{ wordpress_dir }}" 
    owner: ec2-user
    group: ec2-user
    mode: 0755
    recurse: yes
  when: dir_exists.stat.exists == False

- name: Download the latest wordpress
  get_url:
    url: "{{ wordpress_url }}"
    dest: "/tmp/latest.tar.gz"
 
- name: Unzip the downloaded wordpress zipped file
  unarchive:
    src: "/tmp/latest.tar.gz"
    dest: "/tmp"
    copy: no

- name: "Copy the wp-config.php file inside the {{ wordpress_dir }} directory"
  template:
    src: wp-config.php.j2
    dest: "/tmp/wordpress/wp-config.php"

- name: Install wordpress dependencies
  shell: "amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2"

- name: Copy the extracted files to the destination folder
  copy:
    remote_src: yes
    src: "/tmp/wordpress/"
    dest: "{{ wordpress_dir }}"
  register: dir_rename

- name: Reset the permission on Website directory
  file:
    state: directory
    path: "{{ wordpress_dir }}"
    owner: ec2-user
    group: ec2-user
    recurse: yes
  notify: Restart httpd
